dbt-trino:
  outputs:
    dev:
      type: trino
      method: none  # optional, one of {none | ldap | kerberos}
      user: keyhong
      password: [password]  # required if method is ldap or kerberos
      database: hive
      host: localhost
      port: 8080
      schema: dw
      threads: 1

  target: dev
