-- Schema
DROP SCHEMA IF EXISTS HIVE.DW;

CREATE SCHEMA IF NOT EXISTS HIVE.DW;

-- Table 
DROP TABLE IF EXISTS HIVE.DW.DIM_TEST;

CREATE TABLE IF NOT EXISTS HIVE.DW.DIM_TEST (
    TEST                             VARCHAR(14)   COMMENT 'TEST@PK' 
  , DW_LOAD_DT                        TIMESTAMP    COMMENT 'DW적재일시'
) COMMENT 'TEST_TABLE'
WITH (
  format = 'ORC'
)
;

-- Insert Test Data
INSERT INTO HIVE.DW.DIM_TEST VALUES ("TEST1", CURRENT_TIMESTAMP);

-- Select Test Data
SELECT * FROM HIVE.DW.DIM_TEST;
